### ISSUE TITLE
Unable to build Razorpay module

### ISSUE THREAD

**Issue by CharanNampally** [razorpay/razorpay-flutter#123]
I am using Razorpay for my flutter project.
 razorpay_plugin: ^0.3.0 in pubspec
 pod 'razorpay-pod', '1.1.10' in the podfile

## Description
Whenever I tried to build, it fails with the following error
`Xcode's output:
↳
    /Volumes/OS/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_plugin-0.3.0/ios/Classes/SwiftRazorpayPlugin.swift:6:17: error: cannot find type
    'Razorpay' in scope
      var razorpay: Razorpay!
                    ^
    /Volumes/OS/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_plugin-0.3.0/ios/Classes/SwiftRazorpayPlugin.swift:6:17: note: cannot use module
    'Razorpay' as a type
      var razorpay: Razorpay!
                    ^
    /Volumes/OS/flutter/.pub-cache/hosted/pub.dartlang.org/razorpay_plugin-0.3.0/ios/Classes/SwiftRazorpayPlugin.swift:29:24: error: module 'Razorpay' has
    no member named 'initWithKey'
                razorpay = Razorpay.initWithKey(API_KEY!, andDelegate: self )`
                
                
## Flutter Version :
Flutter 1.22.5 • channel stable 

## Xcode Version :
Version 12.0 (12A7209)

## Cocoapod Version :
 'razorpay-pod', '1.1.10'

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
1. Just add the pubspec and podfile and install them
2.Try to build using Xcode 12.0

## Expected Results
Project should have been built successfully

## Snack, code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by Nautiyalsachin** [comment]
Hey @CharanNampally, you have to update the flutter plugin to the latest version.
 
You can do that by removing razorpay-flutter plugin and adding it again, or try updating the existing to the latest version. Let me know if the issue still persists. 

Regards, 
Sachin

**Comment by CharanNampally** [comment]
The issue is resolved with the latest flutter version. You may close this issue.
